"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _workspace_dashboard from './workspace-dashboard.bones.json'
import _workspace_deals from './workspace-deals.bones.json'
import _workspace_deal_detail from './workspace-deal-detail.bones.json'
import _workspace_generic from './workspace-generic.bones.json'

registerBones({
  "workspace-dashboard": _workspace_dashboard,
  "workspace-deals": _workspace_deals,
  "workspace-deal-detail": _workspace_deal_detail,
  "workspace-generic": _workspace_generic,
})
